project:
  type: website
  output-dir: docs

website:
  title: "R Adventures"
  navbar:
    left:
      - href: passport.qmd
        text: Passport
      - href: map.qmd
        text: Adventure Map
      - href: travel_log.qmd
        text: Travel Log
      - href: packing.qmd
        text: Packing List

format:
  html:
    theme: minty
    css: custom.css
    toc: true

editor: visual
